import { randomUUID } from 'node:crypto';
import { isRecord } from '../../shared';
import type { ApiResult } from '../../shared';
import { updateProfile } from '../authApi/profile';
import {
  getCurrentClass,
  listClasses,
  listGrades,
  listSchools,
  selectClass,
} from '../classApi/classes';
import { getProfile, login } from '../authApi/login';
import {
  requireActiveUser,
  requireAdmin,
  requireLogin,
  requireSuperAdmin,
  trustedOpenid,
} from './auth';
import type { Logger, RequestLog } from './audit';
import { AppError, publicErrorCode } from './errors';
import type { Repository } from './repository';
import { failure, success } from './result';
import { identifier, parseAction } from './validate';

export const DOMAIN_ACTIONS = {
  authApi: ['login', 'getProfile', 'updateProfile', 'requestDelete', 'health'],
  classApi: ['listSchools', 'listGrades', 'listClasses', 'selectClass', 'getCurrentClass'],
  audioApi: ['list', 'detail', 'saveProgress', 'history', 'toggleFavorite', 'listFavorites'],
  letterApi: [
    'createDraft',
    'updateDraft',
    'submit',
    'listPublic',
    'detail',
    'listMine',
    'withdraw',
    'delete',
    'report',
  ],
  adminAudioApi: ['createDraft', 'updateDraft', 'publish', 'offline', 'delete', 'listManage'],
  adminApi: [
    'listPendingLetters',
    'reviewLetter',
    'listReports',
    'handleReport',
    'createGrade',
    'createClass',
    'updateClass',
    'grantAdmin',
    'revokeAdmin',
    'getConfig',
    'setConfig',
    'listLogs',
  ],
} as const;

export type Domain = keyof typeof DOMAIN_ACTIONS;
export interface HandlerDependencies {
  repository: Repository;
  getContext: () => unknown;
  getEnvironment: () => string | undefined;
  logger: Logger;
  now?: () => Date;
}

const ACTIVE_USER_ACTIONS = new Set([
  'updateProfile',
  'requestDelete',
  'selectClass',
  'saveProgress',
  'toggleFavorite',
  'createDraft',
  'updateDraft',
  'submit',
  'withdraw',
  'delete',
  'report',
]);

function logSafely(logger: Logger, entry: RequestLog): void {
  try {
    logger.write(entry);
  } catch {
    // A console sink failure cannot expose raw exceptions or change the response contract.
  }
}

export function createHandler(domain: Domain, dependencies: HandlerDependencies) {
  return async (event: unknown): Promise<ApiResult<unknown>> => {
    // Always generated by the server; untrusted client requestId never enters logs.
    const requestId = randomUUID();
    let action = 'unparsed';
    try {
      const parsed = parseAction(event);
      action = parsed.action;
      if (!(DOMAIN_ACTIONS[domain] as readonly string[]).includes(action))
        throw new AppError('INVALID_ARGUMENT');
      const now = dependencies.now?.() ?? new Date();
      let data: unknown;
      if (domain === 'authApi' && action === 'health') {
        const environment = dependencies.getEnvironment();
        if (environment !== 'dev' && environment !== 'test') throw new AppError('FORBIDDEN');
        const context = dependencies.getContext();
        if (!isRecord(context) || typeof context.ENV !== 'string' || !context.ENV)
          throw new AppError('INTERNAL_ERROR');
        await dependencies.repository.checkDatabase();
        data = {
          environment,
          cloudEnvId: context.ENV,
          database: 'reachable',
          checkedAt: now.toISOString(),
        };
      } else {
        const openid = trustedOpenid(dependencies.getContext());
        if (domain === 'authApi' && action === 'login') {
          data = await login(dependencies.repository, openid, now);
        } else if (domain === 'authApi' && action === 'getProfile') {
          data = await getProfile(dependencies.repository, openid);
        } else if (domain === 'authApi' && action === 'updateProfile') {
          data = await updateProfile(
            dependencies.repository,
            openid,
            parsed.payload,
            now,
            requestId,
          );
        } else if (domain === 'classApi') {
          if (action === 'listSchools')
            data = await listSchools(dependencies.repository, openid, parsed.payload);
          else if (action === 'listGrades')
            data = await listGrades(dependencies.repository, openid, parsed.payload);
          else if (action === 'listClasses')
            data = await listClasses(dependencies.repository, openid, parsed.payload);
          else if (action === 'getCurrentClass')
            data = await getCurrentClass(dependencies.repository, openid, parsed.payload);
          else
            data = await selectClass(
              dependencies.repository,
              openid,
              parsed.payload,
              now,
              requestId,
            );
        } else {
          if (domain === 'adminApi' || domain === 'adminAudioApi') {
            // A submitted school is a target to validate, never the source of authority.
            const schoolId =
              parsed.payload.schoolId === undefined
                ? undefined
                : identifier(parsed.payload.schoolId);
            if (action === 'grantAdmin' || action === 'revokeAdmin')
              await requireSuperAdmin(dependencies.repository, openid);
            await requireAdmin(dependencies.repository, openid, schoolId);
          } else if (ACTIVE_USER_ACTIONS.has(action)) {
            await requireActiveUser(dependencies.repository, openid);
          } else {
            await requireLogin(dependencies.repository, openid);
          }
          // Subsequent tasks must validate actual resource school/state before implementing a write.
          // Returning empty arrays or fake writes here would disguise missing business functionality.
          throw new AppError('NOT_IMPLEMENTED');
        }
      }
      logSafely(dependencies.logger, { domain, action, requestId, outcome: 'success' });
      return success(data, requestId);
    } catch (error: unknown) {
      logSafely(dependencies.logger, {
        domain,
        action,
        requestId,
        outcome: 'failure',
        code: publicErrorCode(error),
      });
      return failure(error, requestId);
    }
  };
}
