import { mkdir, readFile } from 'node:fs/promises';
import { buildShared } from './build-shared';
import { writeIfChanged } from './write-if-changed';

const environment = process.env.SHIXUE_ENV ?? 'dev';
if (!['dev', 'test', 'prod'].includes(environment))
  throw new Error('SHIXUE_ENV 必须为 dev/test/prod。');
let values: unknown = {};
try {
  values = JSON.parse(await readFile('config/environments.local.json', 'utf8')) as unknown;
} catch (error: unknown) {
  if (!(error instanceof Error && 'code' in error && error.code === 'ENOENT')) throw error;
}
function record(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
const entry = record(values) ? values[environment] : undefined;
const envId = process.env.SHIXUE_CLOUD_ENV_ID ?? (record(entry) ? entry.envId : '') ?? '';
if (typeof envId !== 'string' || (envId !== '' && !/^[a-zA-Z0-9_-]{1,100}$/.test(envId))) {
  throw new Error('云环境 ID 格式无效。');
}
if (environment !== 'dev' && !envId) throw new Error('test/prod 构建必须配置明确的云环境 ID。');
await mkdir('miniprogram/generated', { recursive: true });
const config = {
  environment,
  envId,
  cloudConfigured: Boolean(envId),
  previewMode: environment === 'dev' && !envId,
};
await writeIfChanged(
  'miniprogram/generated/env.ts',
  `// Generated by prepare:local; do not edit or commit.\nexport const runtimeConfig = ${JSON.stringify(config, null, 2)} as const;\n`,
);
await buildShared();
console.log(
  `本地构建配置：${environment}，${envId ? '已配置云环境' : '仅页面预览，未启用云调用'}。`,
);
